name: Update admin branch

on:
  push:
    branches:
      - main

jobs:
  update-admin-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Merge changes into admin-master branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout admin-master
          git merge main -m "Merge changes from master"
          git push
